---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs-rt-archive
  labels:
    name: gtfs-rt-archive
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gtfs-rt-archive
  template:
    metadata:
      labels:
        name: gtfs-rt-archive
    spec:
      containers:
        - name: app
          image: us.gcr.io/cal-itp-data-infra/gtfs-rt-archive:1.0
          envFrom:
            - configMapRef:
                name: archiver-app-vars
            - configMapRef:
                name: archiver-channel-vars
          volumeMounts:
            - name: agencies-data
              mountPath: /secrets/agencies-data
            - name: gcs-upload-svcacct
              mountPath: /secrets/gcs-upload-svcacct
      volumes:
        - name: agencies-data
          secret:
            secretName: agencies-data
        - name: gcs-upload-svcacct
          secret:
            secretName: gcs-upload-svcacct
