name: Board wrangling

on:
  issues:
    types: [labeled, opened]
  pull_request:

jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:

    - name: add-new-issues-to-repository-based-project-column
      uses: takanabe/github-actions-automate-projects@v0.0.2
      if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'new team member'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/cal-itp/data-infra/projects#workspaces/data-services-current-sprint-620d721f9d810a00186ed9c9/board
        GITHUB_PROJECT_COLUMN_NAME: Backlog
