name: Publish docs to gh-pages

on:
  push:
    branches: [ jupyterbook-documentation ]


jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install python packages
      run: |
        pip install -r airflow/requirements.txt
        pip install git+https://github.com/machow/siuba.git@stable
        pip install jupyter-book==0.12.0
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build docs
      run: jb build docs_jupyterbook

    - name: Save docs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs-build
        path: docs_jupyterbook/_build/html

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs_jupyterbook/_build/html
        publish_branch: dev-docs-jupyterbook
