name: Publish docs to gh-pages

on:
  push:
    branches: [ main ]


jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:

    - name: 'Project gh-pages holobranch'
      uses: JarvusInnovations/hologit@actions/projector/v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HAB_LICENSE: accept
      with:
        holobranch: docs-site
        commit-to: gh-pages
