name: Upload GTFS Schedules to CKAN

on:
  push:
    branches: ["origin/caltrans-geoportal-export"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install python packages
      run: |
        pip install calitp requests

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Run upload
      run: |
        python services/gtfs-ckan-uploader/calitp_data_ca_exporter.py
      env:
        CALITP_CKAN_GTFS_SCHEDULE_KEY: ${{ secrets.CALITP_CKAN_GTFS_SCHEDULE_KEY }}
